### ISSUE TITLE
Prometheus parse problems

### ISSUE THREAD

**Issue by APMarte** [AppMetrics/Prometheus#23] opened 2017-11-22 14:26 UTC
I cant acess metrics from appmetrics in prometheus. 
Can it be parsing error?

level=warn ts=2017-11-22T14:23:50.458732892Z caller=scrape.go:675 component="target manager" scrape_pool=appmetrics target=http://*********/metrics-text msg="append failed" err="no token found"

**Comment by roelandvh** [comment] 2017-11-23 12:01
I seem to have the same issue. The output of the endpoint is the following (just some values replaced).

Metrics endpoint output:
```
# HELP application_httprequests_apdex 
# TYPE application_httprequests_apdex GAUGE
application_httprequests_apdex{server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild"} 1

# HELP application_httprequests_one_minute_error_percentage_rate 
# TYPE application_httprequests_one_minute_error_percentage_rate GAUGE
application_httprequests_one_minute_error_percentage_rate{server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild"} 100

# HELP application_httprequests_one_minute_error_percentage_rate_per_endpoint 
# TYPE application_httprequests_one_minute_error_percentage_rate_per_endpoint GAUGE
application_httprequests_one_minute_error_percentage_rate_per_endpoint{route="GET",server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild"} NaN

# HELP application_httprequests_active 
# TYPE application_httprequests_active GAUGE
application_httprequests_active{server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild"} 0

# HELP application_httprequests_errors 
# TYPE application_httprequests_errors GAUGE
application_httprequests_errors{http_status_code="404",server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild"} 9

# HELP application_httprequests_error_rate_total 
# TYPE application_httprequests_error_rate_total COUNTER
application_httprequests_error_rate_total{server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild"} 9

# HELP application_httprequests_error_rate_per_endpoint_and_status_code_total 
# TYPE application_httprequests_error_rate_per_endpoint_and_status_code_total COUNTER
application_httprequests_error_rate_per_endpoint_and_status_code_total{route="GET",http_status_code="404",server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild"} 9

# HELP application_httprequests_error_rate_per_endpoint_total 
# TYPE application_httprequests_error_rate_per_endpoint_total COUNTER
application_httprequests_error_rate_per_endpoint_total{route="GET",server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild"} 9

# HELP application_httprequests_transactions 
# TYPE application_httprequests_transactions SUMMARY
application_httprequests_transactions_sum{server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild"} 0.17912697
application_httprequests_transactions_count{server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild"} 9
application_httprequests_transactions{server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild",quantile="0.5"} 0.0143838473851932
application_httprequests_transactions{server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild",quantile="0.75"} 0.012762055
application_httprequests_transactions{server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild",quantile="0.95"} 0.101100645
application_httprequests_transactions{server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild",quantile="0.99"} 0.101100645

# HELP application_httprequests_transactions_per_endpoint 
# TYPE application_httprequests_transactions_per_endpoint SUMMARY
application_httprequests_transactions_per_endpoint_sum{route="GET",server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild"} 0
application_httprequests_transactions_per_endpoint_count{route="GET",server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild"} 0
application_httprequests_transactions_per_endpoint{route="GET",server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild",quantile="0.5"} 0
application_httprequests_transactions_per_endpoint{route="GET",server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild",quantile="0.75"} 0
application_httprequests_transactions_per_endpoint{route="GET",server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild",quantile="0.95"} 0
application_httprequests_transactions_per_endpoint{route="GET",server="SOME-PC",app="Some.App",env="development",HostingEnvironment="Development",ApplicationName="Some.Application",ApplicationBuild="SomeApplicationBuild",quantile="0.99"} 0
```

Output of `prometheus --version`:
`prometheus, version 2.0.0 (branch: HEAD, revision: 0a74f98628a0463dddc90528220c94de5032d1a0)`

Prometheus error:
`level=warn ts=2017-11-23T12:01:01.6617151Z caller=scrape.go:673 component="target manager" scrape_pool=bla target=http://localhost/metrics-text msg="append failed" err="no token found"`

Does anyone know whether this is an AppMetrics problem or a Prometheus problem?

**Comment by alhardy** [comment] 2017-11-26 12:04
Should be fixed by https://github.com/AppMetrics/Prometheus/issues/20 haven't yet pushed to nuget.

**Comment by talarari** [comment] 2017-11-29 17:41
Getting the same issue, is a nuget version planned soon?

**Comment by alhardy** [comment] 2017-11-30 07:19
@talarari Not until early in the new year unfortunately, you can reference the latest packages from myget

**Comment by APMarte** [comment] 2017-12-04 16:53
I already solved it in my local machine, the problem is that prometheus can't parse UpperCases so types should be change to 
# TYPE application_httprequests_transactions SUMMARY -> # TYPE application_httprequests_transactions summary

**Comment by narciero** [comment] 2018-01-04 20:01
any update on this? i am unable to use due to windows (CLRF) line endings being used, i am using v2.0.0-alpha and don't see a way to use unix line endings.

**Comment by alhardy** [comment] 2018-01-08 12:11
@narciero will release in the coming weeks

**Comment by martinjt** [comment] 2018-01-21 13:08
I've tried the package on myget and that doesn't appear to be working either.  I've added the line formatting to the options and forced to unix.  I've looked at #21 and that looks like it's just on the text endpoint, when prometheus is using /metric not /metric-text.

I'm using this on a dotnet core 2.0 app, running in a docker container, as is the prometheus instance (v2.1.0).  I've verified that prometheus is hitting the right endpoint, but it's getting the dreaded "No token found" error.

Happy to do some testing if that helps.

**Comment by marcinbudny** [comment] 2018-01-21 19:11
As a workaround, you can use text formatting on /metric endpoint. Confirmed to work with beta packages from myget feed.

**Comment by martinjt** [comment] 2018-01-21 19:13
Funnily enough, that is exactly how I got it working... Hopefully the
protobuf one will be sorted.

**Comment by martinjt** [comment] 2018-01-25 21:52
@alhardy anyword on a new release? would prefer not to use the alpha release on myget if possible.

**Comment by alhardy** [comment] 2018-01-28 12:26
I'm getting to it. Several things to do before a stable release goes out, I'll push out another pre-release sometime soon so you don't have to reference from myget ;)

**Comment by martinjt** [comment] 2018-01-28 12:31
No worries... Let me know if there's anything I can do to help... I can
probably get some time to help with fixes/testing if you need help there.

On 28 Jan 2018 12:26, "Allan Hardy" <notifications@github.com> wrote:

I'm getting to it. Several things to do before a stable release goes out,
I'll push out another pre-release sometime soon so you don't have to
reference from myget ;)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/AppMetrics/Prometheus/issues/23#issuecomment-361059069>,
or mute the thread

**Comment by aensidhe** [comment] 2018-01-29 15:49
https://github.com/prometheus/docs/issues/927 - protobuf is not supported by prometheus 2.0+

**Comment by alhardy** [comment] 2018-02-05 13:07
Seems like it is still undecided? https://github.com/prometheus/prometheus/issues/2788

**Comment by kcameron1973** [comment] 2018-04-25 20:36
I am having a similar issue when my TYPE starts with a numeric value such as "5V_PG" or "01_System_LED".  Is this expected?

Version 2.2.1
Builddate: 20180314014:15:45

**Comment by paulapaulTW** [comment] 2018-04-26 11:04
@martinjt we are experiencing the same issue with our .net core app; you and @marcinbudny mention having a workaround using text formatting - can you provide more details?  

We are trying to aggregate metrics in DataDog (prometheus format), setting up our output formatter this way in Startup.cs:
            IMetricsRoot metricsRoot = null;
            services.AddMetrics(metricsBuilder =>
                {
                    metricsRoot = metricsBuilder.OutputMetrics.AsPrometheusPlainText().Build();
                });
            services.AddMetricsEndpoints(options =>
            {
                 options.MetricsEndpointOutputFormatter = metricsRoot.OutputMetricsFormatters
                     .GetType<MetricsPrometheusTextOutputFormatter>();
            });

**Comment by alhardy** [comment] 2018-04-26 11:34
I should be able to look into this one sometime over the next few days unless someone gets to it before me.

It did appear to be working for me against the latest version of prometheous with this configuration https://github.com/AppMetrics/Prometheus/blob/2.0.0/sandbox/MetricsPrometheusSandboxMvc/Host.cs#L29

**Comment by davisb10** [comment] 2018-09-13 13:41
What is the status of this being fixed? We are trying to use AppMetrics and Prometheus together at my job and have been waiting on this issue to be resolved to proceed.

**Comment by trondhindenes** [comment] 2018-10-31 15:25
Getting the same, and it seems to be caused by AppMetrics upper-casing the metric types.

**Comment by MarcoWesterink** [comment] 2018-11-20 15:54
@trondhindenes Same issue here. as of prometheus 2.4.0 uppercase metric types are no longer supported. @alhardy Can you please push the fix to nuget?

**Comment by AbsorbJonny** [comment] 2018-11-23 16:27
The upper case issue was fixed in response to my bug report here:

https://github.com/AppMetrics/Prometheus/issues/40

But no updated release was prepared to include the fix.

**Closed as completed** 2018-12-02 22:13 UTC
Labels: bug
