### ISSUE TITLE
Health status in /metrics-text endpoint with Prometheus Output Formatter

### ISSUE THREAD

**Issue by kirychenkav** [AppMetrics/Prometheus#29] opened 2018-03-07 12:52 UTC
Hi! I'm happy with App.Metrics functionality, but I have no idea how to make the Grafana's Health gouge to display any data. 

I see, that there is have to be included `application_health_score` to the metrics, but there is no such tags.

How can I include health checks and health status to the metrics?

Thanks

**Comment by alhardy** [comment] 2018-03-07 20:05
Closing this one as it's a duplicate of https://github.com/AppMetrics/Health/issues/9

Planning to do this once .net core 2.1.0 is released as it comes with a 'HostedService' implementation for running background tasks

**Closed as completed** 2018-03-07 20:08 UTC
Labels: duplicate
